### ISSUE TITLE
What the user and password for login

### ISSUE THREAD

**Issue by fajarwahyu99** [tomb1n0/stickets#1]
I want to try and i cant login because not user and password 
![gambar](https://user-images.githubusercontent.com/11350854/37007671-144adb90-2111-11e8-9369-f894d85b6610.png)

**Comment by tomb1n0** [comment]
Hi,

In the create users migration it creates a default user like so:

        // add our default admin user.
        DB::table('users')->insert(
            [
                'name' => 'Tom Harper',
                'email' => 'tom@stickman.co.uk',
                'password' => bcrypt('testing'),
                'admin' => '1',
                'api_token' => str_random(60),
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now()
            ]
        );

This will let you login with tom@stickman.co.uk as the email and testing as the password.

On another note though, i would advise against using this system in any production environment at the moment. There are lots of things wrong with it and i'm likely going to start from scratch with it. There's no tests for a start!

Hope this helps.
